config/crds/solr_v1beta1_solrcloud.yaml
example/test_solrcloud.yaml
pkg/apis/solr/v1beta1/solrcloud_types.go
pkg/controller/util/solr_util.go

Signed-off-by: Zane Williamson <zanew@zillow.com>
Describe your changes
Remove hardcoded memory allocation, and give ability to update jvm parameter.
Testing performed
Tested locally with solrcloud 8.2
Tested to verify present hardcoded value works as default

Making java memory configurable

---

README.md
config/crds/solr_v1beta1_solrbackup.yaml
config/crds/solr_v1beta1_solrcloud.yaml
config/crds/solr_v1beta1_solrprometheusexporter.yaml
example/test_solrcloud_private_repo.yaml
pkg/apis/solr/v1beta1/solrbackup_types.go
pkg/apis/solr/v1beta1/solrcloud_types.go
pkg/apis/solr/v1beta1/solrprometheusexporter_types.go
pkg/controller/solrcloud/solrcloud_controller.go
pkg/controller/util/backup_util.go
pkg/controller/util/solr_util.go

Signed-off-by: Zane Williamson zanew@zillow.com
*Issue number of the reported bug or feature request: #28
Describe your changes
Add optional ability to use a private Docker repo to store and pull SolrCloud images. Requires a predefined K8s secret to reference that is leveraged for accessing private docker repo.
Testing performed
Deployed changes to local development environment and validated image pulls from private Artifactory Docker repository.
Tested using type: kubernetes.io/dockerconfigjson Secret.
Additional context
With this change you can now publish to a private repo SolrCloud images that may contain additional plugins / Jars that your team may be using to extend SolrCloud.

Adding Optional imagePullSecret for private Docker repo access, Fix Missing Statefulset params

---

config/crds/solr_v1beta1_solrcloud.yaml
example/test_solrcloud.yaml
pkg/apis/solr/v1beta1/solrcloud_types.go
pkg/controller/util/solr_util.go

Signed-off-by: Zane Williamson <zanew@zillow.com>
*Issue number of the reported bug or feature request: https://github.com/bloomberg/solr-operator/issues/32
Allow for optional adjustment of the SOLR_OPTS and GC_TUNE environment variables, provide example. Match up with current default behavior.
Allow for tunable logging
Local and development environment testing performed to ensure Solr on 8.2.0 applies the requested parameter changes.

Adding configurable SOLR_OPTS, GC_TUNE, logging

---

config/crds/solr_v1beta1_solrcollection.yaml
example/test_solrcloud.yaml
example/test_solrcollection.yaml
pkg/apis/solr/v1beta1/solrcollection_types.go
pkg/controller/solrcollection/solrcollection_controller.go
pkg/controller/util/collection_util.go

Signed-off-by: Zane Williamson <zanew@zillow.com>
*Issue number of the reported bug or feature request: #42 
Add optional router.field for SolrCollection creation. This isn't modifiable after collection creation.
```
---
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCollection
metadata:
name: example-collection-3-implicit
spec:
solrCloud: example
collection: example-collection-3-implicit-with-router-field
routerName: implicit
routerField: 'car'
autoAddReplicas: true
numShards: 2
replicationFactor: 1
maxShardsPerNode: 1
shards: "fooshard1,fooshard2"
```
Ensured field name showed up in 
```
curl "http://default-example-solrcloud.ing.local.domain/solr/admin/collections?action=CLUSTERSTATUS&collection=example-collection-3-implicit"
```
``` …
```

Adding router.field as optional input for SolrCollection creation

---

config/manager/manager.yaml
config/rbac/kustomization.yaml
config/rbac/leader_election_role_binding.yaml
config/rbac/role_binding.yaml
config/rbac/service_account.yaml

Right now the default service account is used, which gives all controller permissions to every default pod in the default namespace.

Adding a service account when running the operator.

---

controllers/util/solr_util.go

*Issue number of the reported bug or feature request: #66*
Solr Node (individual pod + headless) Services now use the `publishNotReadyAddresses` option. Therefore they can be routed to, even if they are not "ready". This allows us to create a more robust readiness check that protects us during rolling restarts.

Solr Node Services now work when pods not ready.

---

api/v1beta1/solrbackup_types.go
api/v1beta1/solrcloud_types.go
config/manager/manager.yaml
controllers/solrbackup_controller.go
controllers/solrcloud_controller.go
controllers/util/backup_util.go
controllers/util/solr_util.go
example/dependencies/crds.yaml
example/dependencies/operators.yaml
example/test_solrbackup.yaml
example/test_solrcloud.yaml

Signed-off-by: Zane Williamson <zanew@zillow.com>
*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
**Additional context**
Add any other context about your contribution here.

Fixing Rest config NPE & ZK Persistence Reconciling/Defaulting & Backup/Restore Volume mount

---

controllers/solrcollection_controller.go
controllers/util/collection_util.go

*Issue number of the reported bug or feature request: #49*
MaxShardsPerNode is taken into account when updating a collection, however not when a collection is being created. This is a fix for that.

Adding in maxShardsPerNode when creating collection.

---

api/v1beta1/solrcloud_types.go
config/crd/bases/solr.bloomberg.com_solrclouds.yaml
controllers/solrcloud_controller.go
helm/solr-operator/crds/crds.yaml

*Issue number of the reported bug or feature request: Resolves #88*
Adding an entry to the SolrNodeStatus for the name of the kubernetes node that the pod is running on.
Ran on a cluster and the nodeName information was populated correctly.

Add Kubernetes NodeName information to SolrNode status

---

controllers/util/collection_util.go

*Issue number of the reported bug or feature request: Fixes #91*
Fixes an error in logging bad parameters for the `routerName` parameter of a SolrCollection.

Fixing logging in collection util.

---

api/v1beta1/solrcollection_types.go
config/crd/bases/solr.bloomberg.com_solrcollections.yaml
controllers/solrcollection_controller.go
controllers/util/collection_util.go
helm/solr-operator/crds/crds.yaml

*Issue number of the reported bug or feature request: Fixes #97*
`routerField` is no longer added to the Solr Collections API call if it is empty.
Also changed `routerName` to be an enum, as there are only 2 possible options for this field.

Fixed usage of empty routerField and made routerName an enum.

---

api/v1beta1/solrcloud_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/solr.bloomberg.com_solrclouds.yaml
controllers/util/zk_util.go
example/test_solrcloud_toleration_example.yaml
helm/solr-operator/crds/crds.yaml

Signed-off-by: Zane Williamson <zanew@zillowgroup.com>
Adding support for tolerations and node selector for Zookeeper

bug: adding missing inputs for zk tolerations and node selector support

---

.gitignore
Makefile
docs/charts/index.yaml
docs/development.md
docs/release-instructions.md
hack/setup_release.sh
helm/solr-operator/Chart.yaml
helm/solr-operator/LICENSE
helm/solr-operator/README.md
helm/solr-operator/values.yaml

This is a PR to host a helm repo in the github pages of this github repository (bloomberg.github.io/solr-operator/charts). 
I still need to fix the documentation in the getting started, and add documentation around doing releases. But I think the logic should be there.

Adding hosted helm chart with deployment script.

---

Makefile
docs/charts/index.yaml
hack/release/build_helm.sh
hack/release/setup_release.sh
hack/release/update_versions.sh
helm/solr-operator/Chart.yaml

This includes hosted kubernetes versions, like EKS and GKE
There is an issue in the Kubernetes versions for EKS and GKE, where they append other information in the version that makes semVer think it is a pre-release. Therefore the following version check fails, because the greater than enforces that a version must be a full release, not a pre-release.
```yaml
kubeVersion: ">= 1.13.0"
```
If we set the compared version to be a pre-release, like `1.13.0-0`, then the `>=` will match pre-release versions as well.
More info can be found here: https://github.com/helm/helm/issues/3810

Allow "pre-release" Kube versions in Helm chart

---

Makefile
config/manager/manager.yaml
hack/helm/copy_crds_roles_helm.sh
hack/release/update_versions.sh
helm/solr-operator/README.md
helm/solr-operator/templates/_helpers.tpl
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/templates/role.yaml
helm/solr-operator/templates/role_binding.yaml
helm/solr-operator/templates/service_account.yaml
helm/solr-operator/values.yaml
main.go

*Issue number of the reported bug or feature request: Resolves #118 Resolves #119*
This PR allows for the solr operator to be deployed to a specific namespace using the helm chart.
This can be done with `helm install --namespace <ex>`.
The ability to watch specific namespaces has also been added via the `watchNamespaces` helm variable, as well as the `--watch-namespaces` option to the solr operator program.
If neither is provided, then the operator will watch the entire kubernetes cluster (all namespaces).
There are also now parameters for creating RBAC/ServiceAccounts.
I have installed the operator with many different configurations manually using the helm chart.

Adding ability to deploy helm chart to a namespace.

---

controllers/solrcloud_controller_externaldns_test.go
controllers/solrcloud_controller_ingress_test.go
controllers/solrcloud_controller_test.go
controllers/util/solr_util.go

*Issue number of the reported bug or feature request: Resolves #121*
Instead of relying on the killing of solr instances through general kubernetes mechanisms, we can use the built in STOP_PORT for Solr to perform graceful shut downs whenever a pod is killed.
More testing needs to be performed before this PR can be merged.

Adding use of stop port to run before killing pods.

---

api/v1beta1/solrbackup_types.go
api/v1beta1/solrcloud_types.go
api/v1beta1/solrcollection_types.go
api/v1beta1/solrcollectionalias_types.go
api/v1beta1/solrprometheusexporter_types.go
config/crd/bases/solr.bloomberg.com_solrbackups.yaml
config/crd/bases/solr.bloomberg.com_solrcollectionaliases.yaml
config/crd/bases/solr.bloomberg.com_solrcollections.yaml
helm/solr-operator/crds/crds.yaml

Small change to specify scope on all of the generated CRDs.

Adding scope: Namespaced to all CRDs.

---

controllers/solrcloud_controller.go
controllers/solrcloud_controller_test.go

*Issue number of the reported bug or feature request: Fixes #129*
Generate a proper ZkConnectionString when using a provided ZK Cluster.
Unit tests have been changed to use the expanded zkConnectionString.

ZookeeperConnection string now uses all ZK hosts.

---

README.md
api/v1beta1/solrcloud_types.go
controllers/solrcloud_controller.go
controllers/solrcloud_controller_externaldns_test.go
controllers/solrcloud_controller_ingress_test.go
controllers/solrcloud_controller_test.go
controllers/solrprometheusexporter_controller_test.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go

*Issue number of the reported bug or feature request: Fixes #141, #142*
Two issues are fixed here:
1. The portName and targetPort for SolrCloud services have been changed to have the same name. This fixes issues with certain cloud providers that have bugs with regard to that. (#141)
1. The SolrCloud status object had multiple issues with the urls it displayed for users to connect with. (#142)
Unit tests have been modified to ensure that these values are now correct in the future.

Use same portName as targetPort in service and fix Status bugs.

---

api/v1beta1/solrcloud_types.go
controllers/solrcloud_controller.go
controllers/solrcloud_controller_test.go
controllers/util/solr_util.go
controllers/util/zk_util.go
go.mod

*Issue number of the reported bug or feature request: Fixes #139*
Currently the Solr Operator takes responsibility of connecting to a ZK instance and ensuring that the given chRoot exists before creating a SolrCloud StatefulSet to connect to that ZKConnectionString. This can be problematic for various reasons, mentioned in #139.
Instead move the logic into a postStart hook. Therefore everytime a Solr pod starts it will use `bin/solr` logic to check to see if the ZK can be connected to and if the chroot exists. If not, it will attempt to create the chroot.
If ZK ACL information have already been loaded into the pod, then these will work with the `bin/solr` commands to connect to ZK and check/create the Chroot.
Unit testing added to ensure the …

Move Chroot creation logic from the operator to a postStart hook

---

api/v1beta1/common_types.go
api/v1beta1/solrcloud_types.go

*Issue number of the reported bug or feature request: Fixes #136*
The default for new resources managed by the solr operator is to not have an imagePullPolicy specified, allowing the default kubernetes policy to take affect.
Tested locally

Remove default imagePullPolicy

---

api/v1beta1/common_types.go
config/crd/bases/solr.bloomberg.com_solrclouds.yaml
config/crd/bases/solr.bloomberg.com_solrprometheusexporters.yaml
controllers/controller_utils_test.go
controllers/solrcloud_controller_test.go
controllers/solrprometheusexporter_controller_test.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go
controllers/util/zk_util.go
helm/solr-operator/crds/crds.yaml

Add the ability for users to set priorityClassNames for their pods.
Custom PriorityClassName tests added to the unit tests for both SolrClouds and SolrPrometheusExporters.

Adding PriorityClassName in podOptions.

---

api/v1beta1/common_types.go
config/crd/bases/solr.bloomberg.com_solrclouds.yaml
config/crd/bases/solr.bloomberg.com_solrprometheusexporters.yaml
controllers/solrcloud_controller.go
controllers/solrcloud_controller_test.go
controllers/util/solr_util.go
go.sum
hack/install_dependencies.sh
helm/solr-operator/crds/crds.yaml

Signed-off-by: Timothy Potter <thelabdude@gmail.com>
This fixes https://github.com/bloomberg/solr-operator/issues/86
Introduce a new var `ProvidedConfigMap` in the `CustomSolrKubeOptions.ConfigMapOptions` to allow users to supply the name of a ConfigMap containing a custom `solr.xml`. If supplied, we track the MD5 checksum of the `solr.xml` data in an annotation on the pod spec (`solr.apache.org/solrXmlMd5`) for the StatefulSet to trigger a rolling restart when the `solr.xml` in the `ConfigMap` changes. If supplied on the `SolrCloud` CRD, the controller requires the provided `ConfigMap` to contain a `solr.xml` that **must** have a placeholder for the operator to set the `hostPort` variable, e.g. 
```
<int name="hostPort">${hostPort:80}</int>
```
Includes a unit test that verifies proper …

Use solr.xml from provided ConfigMap

---

api/v1beta1/solrcloud_types.go
config/crd/bases/solr.bloomberg.com_solrclouds.yaml
helm/solr-operator/crds/crds.yaml

*Issue number of the reported bug or feature request: #169*
Made the two new Status fields in v0.2.7 optional:
- Status.upToDateNodes
- Status.nodes.specUpToDate
Manually tested with upgrading the CRDs to v0.2.7 (with this fix), then upgrading the operator to v0.2.7

Fixing upgrade issue with new Status fields.

---

README.md
docs/development.md

Part of: #183 
Fix Bloomberg references.
Things pending:
- Docker Pulls - need to wait until we push an image to docker hub
- Slack - should we cross ref the Lucene/Solr one too?
- Contributing Guidelines - should we link this here? https://cwiki.apache.org/confluence/display/solr/HowToContribute ? This isn’t a 100% correct considering building and running are completely different for the operator. We need a new doc for this perhaps?

Cleanup README.md

---

controllers/solrprometheusexporter_controller.go
controllers/solrprometheusexporter_controller_test.go
controllers/suite_test.go
controllers/util/prometheus_exporter_util.go

Allow users to override the Prometheus exporter config (XML) via a user-provided ConfigMap supplied via the existing `prometheusExporter.Spec.CustomKubeOptions.ConfigMapOptions.ProvidedConfigMap` setting.
Keep the md5 hash of the custom config XML in an annotation on the pod spec of the deployment so that a rolling restart is triggered when the configuration changes.

Override Prometheus exporter config XML via a user-supplied ConfigMap

---

README.md
docs/local_tutorial.md
docs/running-the-operator.md
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md

A part of #183 .
This is a stable artifactHub location, and will not change whenever the repo moves.
The artifactHub will also contain the docs for released Helm chart images, so users will not have to use the unstable documentation at `/helm`.
I will be going and backporting documentation for old helm charts to update urls that are no longer available.

Update helm docs, and add link to new artifactHub.

---

api/v1beta1/common_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
config/crd/bases/solr.apache.org_solrprometheusexporters.yaml
controllers/controller_utils_test.go
controllers/solrcloud_controller_test.go
controllers/solrprometheusexporter_controller_test.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go
go.sum
helm/solr-operator/crds/crds.yaml

Currently you can only specify a single imagePullSecret in the ContainerImage, for the SolrImage in SolrCloudSpec. This allows a user to define any number of imagePullSecrets, which is required if initContainers or sidecarContainers need different imagePullSecrets to the SolrImage.

NT: Allow the definition of multiple imagePullSecrets.

---

controllers/solrcloud_controller.go
controllers/solrcloud_controller_tls_test.go
controllers/util/common.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go
go.sum

Resolves #214 
Replaces the _k8s.io/api/extensions/v1beta1_ `Ingress` with the _k8s.io/api/networking/v1beta1_ `Ingress`.
Initially I tried to replace with _k8s.io/api/networking/v1_, however that is not stable until Kubernetes v1.19. So we will want to wait to upgrade to v1 until our minimum supported Kubernetes version is v1.19.

Use k8s.io/api/networking/v1beta1 Ingress.

---

controllers/solrcloud_controller.go
controllers/solrprometheusexporter_controller.go
controllers/util/common.go
go.mod

Relates to #222 
This change is necessary if in-place updates from Bloomberg resources to Apache resources are to succeed.
With this change, resources created for Bloomberg SolrClouds can be claimed and re-controlled by Apache SolrClouds.
This does make new resource management code more complex, but it is a good feature to have, probably.

Update the owner reference of owned resources, if the reference is not correct

---

hack/helm/copy_crds_roles_helm.sh
hack/install_dependencies.sh
helm/solr-operator/crds/crds.yaml

`make manifests` no longer relies on Kustomize. This means that our checks are not broken by inconsistencies between different versions of Kustomize.

Upgrade kustomize. Modernize helm manifest generation.

---

docs/local_tutorial.md
docs/running-the-operator.md
docs/upgrade-notes.md
docs/upgrading-to-apache.md
hack/headers/zookeeper-operator-header.yaml.txt
hack/release/setup_release.sh
hack/test-upgrade.sh
helm/solr-operator/README.md
helm/solr-operator/values.yaml

Resolves #222 
This includes a test that installs v0.2.6, upgrades to v0.2.8 and then upgrades to v0.3.0.
The documentation gives two options, upgrading in an environment managed manually, and an environment managed via a system like Ansible.

Help for upgrading from v0.2.x to v0.3.0

---

hack/test-upgrade.sh

Both https://raw.githubusercontent.com/apache/lucene-solr-operator/v0.2.8/helm/solr-operator/crds/crds.yaml and https://raw.githubusercontent.com/apache/solr-operator/v0.2.8/helm/solr-operator/crds/crds.yaml seem to work in-browser but the latter might be clearer?

[lucene-]solr-operator change in test-upgrade.sh

---

.gitignore
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml

This adds the following options in the Solr Operator helm chart:
- labels
- annotations
- nodeSelector
- affinity
- tolerations
- priorityClassName
- sidecarContainers
The Solr Operator container resources also no longer have a default value.

Add more pod options in the Solr Operator helm chart.

---

api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
controllers/solrcloud_controller.go
controllers/solrcloud_controller_test.go
docs/local_tutorial.md
helm/solr-operator/crds/crds.yaml

This fixes #251 
A user should be able to scale the SolrCloud CR using HPA:
```yaml
...
spec:
maxReplicas: 6
minReplicas: 3
scaleTargetRef:
apiVersion: solr.apache.com/v1beta1
kind: SolrCloud
name: my-solr-cluster
metrics:
....
```
Field `spec.replicas` from the SolrCloud CR should be left unset (it's already optional) if HPA is used, just like for deployment replicas field and HPA. 
The HPA has to be defined separately and it's not part of the Operator, thus, the user is responsible for choosing the metrics and the logic of HPA.

Add support for HPA

---

api/v1beta1/solrcloud_types.go
controllers/solrcloud_controller_tls_test.go
docs/upgrade-notes.md
helm/solr-operator/Chart.yaml
helm/solr/Chart.yaml
helm/solr/values.yaml

Resolves #285
Upgrades the default Solr version to `8.9` from `7.7.0`.
No existing `SolrCloud` or `SolrPrometheusExporter` resources will be effected by this change, only new resources created after the Solr Operator is upgraded.

Upgrade default Solr version to 8.9

---

api/v1beta1/common_types.go
api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
config/crd/bases/solr.apache.org_solrprometheusexporters.yaml
controllers/controller_utils_test.go
controllers/solrcloud_controller_test.go
controllers/solrprometheusexporter_controller_test.go
controllers/util/common.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go
controllers/util/zk_util.go
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml
helm/solr-operator/values.yaml
helm/solr/Chart.yaml
helm/solr/README.md
helm/solr/templates/_custom_option_helpers.tpl
helm/solr/templates/_helpers.tpl
helm/solr/templates/_zk_helpers.tpl
helm/solr/templates/service_account.yaml
helm/solr/templates/solrcloud.yaml
helm/solr/values.yaml

Resolves #264 
The option will be available for:
- SolrCloud pods
- Provided ZK Cluster pods
- SolrPrometheusExporter pods
**SolrCloud CRD**
```yaml
spec:
customSolrKubeOptions:
podOptions:
serviceAccountName: "...."
zookeeperRef:
provided:
zookeeperPodPolicy:
serviceAccountName: "...."
```
**SolrPrometheusExporter CRD**
```yaml
spec:
customKubeOptions:
podOptions:
serviceAccountName: "...."
```
This is enabled multiple places in the **Solr Helm Chart**:
```yaml
serviceAccount:
create: false
name: ""
podOptions:
serviceAccountName: ""
zk:
provided:
zookeeperPodPolicy:
serviceAccountName: ""
```

Ability to customize serviceAccountName for SolrCloud and SolrPrometheusExporter

---

Makefile
api/v1beta1/solrcloud_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/solr.apache.org_solrclouds.yaml
controllers/controller_utils_test.go
controllers/solrcloud_controller_test.go
controllers/solrcloud_controller_zk_test.go
controllers/util/zk_util.go
controllers/util/zk_util_test.go
docs/solr-cloud/solr-cloud-crd.md
docs/upgrade-notes.md
go.sum
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml
helm/solr/README.md
helm/solr/templates/solrcloud.yaml
helm/solr/values.yaml

Resolves: #259
Adds an option for the storage type of the provided ZK cluster. `Ephemeral` or `Persistent`.
If the user does not provide either option, then the Solr Operator will use whatever type is used by the Solr pods. (which defaults to `ephemeral` if none is provided).
Since https://github.com/pravega/zookeeper-operator/pull/215 was merged, the Zookeeper Operator has had the ability to deploy Zookeeper with Ephemeral Storage. All we have to do is provide this as an option through the SolrCloud CRD, and solr helm chart.
This is a breaking change that requires a note in the Upgrade Notes, because the ZK storage now defaults to `ephemeral` if a user is using ephemeral storage for Solr. In previous versions of the Solr Operator, only persistent ZK storage is supported, so this is …

Add ephemeral option for zk storage.

---

build/Dockerfile
helm/solr-operator/Chart.yaml

Resolves #294
I reached my limit of `docker scan` for this month, but the base image has no vulnerabilities, so we should be down to 2 given the vulnerabilities listed for the solr-operator binary here:
https://artifacthub.io/packages/helm/apache-solr/solr-operator?modal=security-report
The difference between `distroless/base` and `distroless/static` is mainly for the purpose of [including `libc`](https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md) for go programs that use `cgo`, [such as through the `net` package](https://pkg.go.dev/net#hdr-Name_Resolution).
Since the Solr Operator is built with `CGO_ENABLED=false`, we do not need `libc`, so we should be find to base our image on `distroless/static`.

Change base image of Solr Operator to distroless/static

---

Makefile

Resolves #296
Now that the ArtifactHub `ah` validation tool is official, we can add ArtifactHub validation to our `make helm-check`, thus ensuring that all changes made to the helm charts are safe with regards to the ArtifactHub metadata!

Add artifactHub validation in helm-check

---

controllers/controller_utils_test.go
controllers/solrcloud_controller_test.go
controllers/solrprometheusexporter_controller_test.go
controllers/suite_test.go
controllers/util/common.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go
helm/solr-operator/Chart.yaml

Resolves #282 
I also went ahead and simplified the way that Probe customization is done in the code. Startup Probes are now tested as well, as apparently they had not been tested previously.

Ability to customize probes for the PrometheusExporter

---

controllers/util/solr_util.go
docs/solr-cloud/solr-cloud-crd.md
helm/solr-operator/Chart.yaml

Fixes #274 and #289 
Very minor change to remove the `users` role from the `all` permission, move the `all` permission to the last index in the json file, and add a new rule for the `/admin/zookeeper/status` path needed for updates to the exporter in 8.9 (see #289 )
Manual integration-style testing required:
Create a SolrCloud running Apache Solr 8.9.0, created a collection, and then tried to index some docs as the `solr` user, which now fails with a 403 ~ Unauthorized. Indexing as the `admin` user works. The `solr` user can log in to the Admin UI but can only query collections. 
Also verified the Prometheus exporter (also running 8.9) can now retrieve metrics when basic auth is enabled.

Fix initial security.json rbap rules

---

controllers/controller_utils_test.go
controllers/solrcloud_controller.go
controllers/solrcloud_controller_tls_test.go
controllers/solrprometheusexporter_controller.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_tls_util.go
controllers/util/solr_util.go

Fixes #308 
Consolidated most of the TLS related utility code into a new file in the `util` package: `solr_tls_util.go`
All the TLS related config (env vars, annotations, initContainers, volumes/mounts) get appended to the config for a `StatefulSet` or `Deployment` in one step at the end vs. being infused at various places in `GenerateStatefulSet` and `GenerateSolrPrometheusExporterDeployment`. I like this approach because most of the TLS config is additive. There are a few places where we have to be careful about overriding previous settings (such as the `entrypoint` for the exporter when using the `mountedServerTLSDir` but that's only in a few small places).
There's also a lot of common logic for configuring the StatefulSet (for SolrClouds) and Deployment (for exporter), so I refactored …

Refactor TLS setup code into a separate file and consolidate logic between the StatefulSet and exporter Deployment

---

build/NOTICE-ADDITION
controllers/util/solr_api/api.go
docs/running-the-operator.md
go.mod
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml
main.go

Fixes #317 
Use `fsnotify` to watch the mTLS `tls.crt` file (mounted from a secret) to hot reload the certificate for the Http client used to make calls to Solr.
For files loaded from a secret, the watched file will be a symlink that gets removed and re-added when the underlying secret changes. Thus, our watcher responds to a REMOVE event on the symlink to reload the certificate. It also supports a WRITE event if the watched file is not a symlink, which is probably not needed right now but may be useful in the future when TLS certs get loaded from a CSI driver or other type mechanism.
Manual testing for now by configuring a self-signed cert for the operator pod and then updating it via cert-manager, which triggers the cert to get re-issued and the secret to get updated. K8s handles …

Option to watch for updates to the mTLS cert used by the operator to call Solr pods

---

helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml

Resolves #307 
This does not use the protected metrics-endpoint described in the [kubebuilder docs](https://kubebuilder.io/reference/metrics.html#protecting-the-metrics). This is also just using the default operator metrics. We can add additional metrics in future PRs.
The metrics have been enabled since #321 was implemented, but not when using the helm chart. This fixes that.

Enable Solr Operator metrics when using the helm chart.

---

controllers/solrbackup_controller.go
controllers/util/solr_security_util.go

Was a bug introduced when refactoring the security code, basically need to call the `solrCloud.BasicAuthSecretName()` method. Tested in live EKS cluster and backup API requests are now working.

Properly resolve the name of the basic auth secret for a SolrCloud when calling the backup API

---

config/manager/manager.yaml
helm/solr-operator/Chart.yaml
helm/solr-operator/templates/deployment.yaml

Fixes #389 
This was previously specified on the Solr Operator pod, meaning that all sidecar containers also had to run as non-root, although that might not be possible. To make this work as best as possible for everyone, we only know that the Solr Operator image uses a non-root user, so we will only specify this option on the Solr Operator container.

Move runAsNonRoot to container securityContext.

---

docs/solr-prometheus-exporter/README.md

Fix solr prometheus exporter Doc. It should be `passwordKey `.

Fix solr prometheus exporter Doc

---

Makefile
config/crd/bases/solr.apache.org_solrbackups.yaml
config/crd/bases/solr.apache.org_solrclouds.yaml
config/crd/bases/solr.apache.org_solrprometheusexporters.yaml
config/dependencies/zookeeper_cluster_crd.yaml
hack/config/add_crds_annotations.sh
hack/config/add_crds_roles_headers.sh
hack/release/artifacts/create_crds.sh
hack/release/version/propagate_version.sh
hack/release/wizard/scriptutil.py
hack/zk-operator/update-crd.sh
helm/solr-operator/crds/crds.yaml

Add an annotation to our CRDs that will make ArgoCD replace instead of apply.
I have edited the three base CRDs, and also the dependency ZK CRD, but that is fragile, since the ZK crd may be overwritten on next upgrade...

Add operator version & ArgoCD annotations to CRDs

---

docs/solr-cloud/solr-cloud-crd.md
example/test_solrcloud_addressability.yaml
helm/solr/Chart.yaml
helm/solr/README.md
helm/solr/values.yaml

This is a part of #412, fixing the documentation and examples in the next bug-fix release before the field can have a better name in the next minor release.

Fix documentation and example for additionalDomains

---

helm/solr/README.md

I have corrected the Helm description of the **solrOptions.javaMemory** key. I think it was accidentally copied from the above description of the key **busyBoxImage.imagePullSecret**.

Corrected Helm description solrOptions.javaMemory

---

helm/solr-operator/Chart.yaml
helm/solr-operator/templates/leader_election_role_binding.yaml

Found that I was getting errors like:
```
error retrieving resource lock mynamespace1/88488bdc.solr.apache.org: leases.coordination.k8s.io "88488bdc.solr.apache.org" is forbidden: User "system:serviceaccount:system:solr-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "mynamespace1"
```
I have deployed with the following values:
```
watchNamespaces: mynamespace1,mynamespace2
```
When I did a helm diff to switch off leader elections, I saw something like the following in the diff:
```
- # Source: solr-operator/templates/leader_election_role_binding.yaml
...
- apiVersion: rbac.authorization.k8s.io/v1
- kind: RoleBinding
- metadata:
-   name: solr-operator-leader-election-rolebinding
-   namespace: mynamespace1
- roleRef:
-   apiGroup: …
```

Helm chart: fix rolebindings when watching multiple namespaces

---

docs/upgrade-notes.md

Still need to figure out if v0.6.x is compatible with 9.0 (and probably need to test the earlier versions as well to add to the matrix)

Add version matrix entry for v0.6.x

---

api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
docs/solr-cloud/solr-cloud-crd.md
example/test_backup_gcs.yaml
example/test_backup_volume.yaml
helm/solr-operator/crds/crds.yaml
helm/solr/README.md
helm/solr/templates/solrcloud.yaml
helm/solr/values.yaml

The CRD option had been removed from 0.6.0 by a prior commit but a few
dangling references still remainined.  This cleans those up to help
clarify the docs around backup functionality.

Remove remaining 'backupRestoreOptions' references

---

Makefile

There is no arm64 artifact for our current version of kubebuilder-tools,
which causes test setup to fail on M1 machines.  However, the amd64
artifact offered by kubebuilder seems to work well enough for our
purposes, so we can use that as a workaround until we're able to upgrade
kubebuilder-tools down the road.

Use GOARCH=amd64 when testing on 'Apple Silicon'

---

docs/solr-backup/README.md

Previous version implied solr had to be less than 8.9.0, but incremental backup is introduced in 8.9.0. Instead of “or older” vs “or newer” >= 8.9.0 is used, as this is more clear for non native English speakers and matches other version info in the document.

Repeating Backup Solr Version is confusing

---

helm/solr/README.md

This `affinity` key is listed twice in the table, removing the one with wrong type and description

Remove redundant docs for zk.provided.zookeeperPodPolicy.affinity

---

helm/solr-operator/Chart.yaml
helm/solr-operator/templates/service_account.yaml
helm/solr-operator/values.yaml
helm/solr/Chart.yaml
helm/solr/templates/service_account.yaml
helm/solr/values.yaml

In order to support AWS IAM Role assumption via the [pod-identity-webhook](https://github.com/aws/amazon-eks-pod-identity-webhook), there need to be annotations added to the ServiceAccount.
This change enables users to add annotations to the ServiceAccount created for the SolrCloud instance.

Add Annotations to created ServiceAccount

---

helm/solr/README.md

Also specify that changing to another version of the zookeeper image will not work (since zookeeper-operator [hard-codes the start script to `/usr/local/bin/zookeeperStart.sh`](https://github.com/pravega/zookeeper-operator/blob/master/pkg/zk/generators.go#L156) and that script is pravega-specific and does not exist in e.g. the official zookeeper image.

Fix typo in readme

---

hack/config/copy_crds_roles_helm.sh
helm/solr-operator/Chart.yaml
helm/solr-operator/templates/_helpers.tpl
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/templates/leader_election_role.yaml
helm/solr-operator/templates/leader_election_role_binding.yaml
helm/solr-operator/templates/role.yaml
helm/solr-operator/templates/role_binding.yaml
helm/solr-operator/templates/service_account.yaml
helm/solr/Chart.yaml
helm/solr/templates/service_account.yaml
helm/solr/templates/solrcloud.yaml
main.go

There are a few issues with namespaces in the helm chart.
- Some resources use the current context's namespace instead of the release namespace.
- The helm chart sets RBAC for leader election in all watched namespaces. Only 1 namespace is necessary

Fix issue with namespaces in helm charts

---

controllers/zk_api/zkcluster.go
docs/upgrade-notes.md
helm/solr-operator/Chart.yaml

There is no reason why the zookeeper image would need an aggressive imagePullPolicy, especially since we are not using the `latest` tag. The default tag is set to the version of the zookeeper-operator that is supported by the Solr Operator.

Zookeeper image should not default to pull Always

---

controllers/solrbackup_controller.go
helm/solr-operator/Chart.yaml

https://github.com/apache/solr-operator/pull/455 introduced a bug for non-recurring backups that was unearthed while working on https://github.com/apache/solr-operator/pull/507
Basically we need to only update the `NextScheduledTimestamp` if `recurrence` is enabled.
I also restructured the logic to hopefully make it more clear when backup logic should be run.

Fix non-recurring backups

---

controllers/solrbackup_controller.go
controllers/util/backup_util.go
controllers/util/solr_api/api.go
docs/solr-backup/README.md
helm/solr-operator/Chart.yaml

Resolves #515.
When there are no collections specified in the CRD, attempt to list them all from SolrCloud and back them up.

Fix SolrBackup not taking backups when the collections field is omitted 

---

docs/local_tutorial.md

Updating the version of the Autoscaler as it's deprecated. 
`Warning: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler`
And fixing the apiVersion as it's '.org' and not '.com'
```
% kubectl api-resources -o wide | grep SolrCloud
solrclouds                        solr          solr.apache.org/v1beta1                true         SolrCloud 
```

Use HPA v2 in tutorial

---

controllers/solrcloud_controller_zk_test.go
controllers/util/zk_util.go
helm/solr-operator/Chart.yaml

Resolves #490
The fix for Zookeeper pod labels is no longer necessary since #549 has been merged in for the `v0.7.0` release. We can go back to using the native Zookeeper operator logic to set pod labels.

Remove pod labels fix after zk-op upgrade

---

helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml

In order to comply to security policies (such as from Kyverno), make the k8s `securityContext` configurable via the helm chart values.

Make security context configurable.

---

.gitignore
go.mod
tests/e2e/suite_test.go
tests/e2e/test_utils_test.go

- Save Solr Operator logs for each test (filtered to only the applicable lines for that test)
- Print the log directory on failure
- Include the KUBERNETES_VERSION on failure-retry scripts.

Integration Test improvements

---

controllers/solr_cluster_ops_util.go
controllers/solr_pod_lifecycle_util.go
controllers/util/solr_update_util.go
controllers/util/solr_update_util_test.go
helm/solr-operator/Chart.yaml

There was a bug introduced at some point, that once a deletion of a node was determined, if there was an error while moving replicas off of the node, then the operator was likely to delete the pod without retrying to move the replicas.
I've restructured the logic around fetching cluster state information, so that its very clear where the information is coming from when making these choices.

Fix rolling restarts

---

api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
config/crd/bases/solr.apache.org_solrprometheusexporters.yaml
controllers/solrcloud_controller_tls_test.go
controllers/util/solr_tls_util.go
docs/solr-cloud/solr-cloud-crd.md
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml
helm/solr/README.md
helm/solr/values.yaml

Resolves #603
The Cert Manager CSI Driver only accepts a string password when creating pkcs12 keystores, so we need to support this.
This will be tested by #605 , which isn't great, but any issues will be fixed there.
TODO:

Add option for explicit keystore/truststore password for mountedDir

---

tests/scripts/manage_e2e_tests.sh

SOLR-16933 has been fixed for 9.4, but still exists in earlier releases in the 9.x line where it causes a number of e2e tests to fail their assertions.
This commit is meant to workaround this problem until a 9.4 docker image is available by defaulting the e2e tests to Solr 8.11.2

Default to Solr 8.11 for e2e tests

---

controllers/util/solr_util.go
helm/solr/Chart.yaml

This allows us to take advantage of the additional "safety-valve" setting added in SOLR-13336 back in Solr 8.1!

Add maxBooleanClauses setting to default solr.xml

---

controllers/solrprometheusexporter_controller_test.go
controllers/util/prometheus_exporter_util.go
docs/solr-prometheus-exporter/README.md

In recent versions of Solr (>=8.8) the prometheus exporter has an env-var equivalent for each CLI argument taken by its start script.
This commit switches the operator over to providing values using this env-var capability where possible.  Hopefully this makes the created resources a little cleaner and easier-to-read for administrators and users.
Closes #638

Pass exporter args as env vars where possible

---

controllers/solrcloud_controller.go
controllers/solrcloud_controller_backup_test.go
controllers/solrcloud_controller_externaldns_test.go
controllers/solrcloud_controller_ingress_test.go
controllers/solrcloud_controller_test.go
controllers/solrcloud_controller_zk_test.go
controllers/util/solr_util.go
controllers/util/solr_util_test.go
docs/solr-cloud/solr-cloud-crd.md
docs/upgrade-notes.md
helm/solr/Chart.yaml

The default solr.xml now has the necessary plumbing to obey the commonly used `solr.sharedLib`, `solr.allowPaths`, and `enableMetrics` system properties.
Resolves #635

Add sysprop driven XML tags to default solr.xml

---

tests/scripts/manage_e2e_tests.sh

This overrides #632 
Solr 9.4 has been released and fixes issues that caused incompatibility with the Solr Operator.
The smoke tests use Solr 8.11, so its safer to default to 9.4 so that we test both 8.11 and 9.4 more often.

Use 9.4 as the default e2e-tests Solr version

---

docs/local_tutorial.md

A contributor pointed out the tutorial no longer worked with operator 0.8.0 because some of the solr.xml changes made recently conflicted with the Solr version that the tutorial was using (8.3).
This commit updates the tutorial to use a Solr version within the range accepted by operator 0.8.0

Update Solr version tag in local_tutorial.md

---

api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
controllers/solr_cluster_ops_util.go
controllers/solrcloud_controller.go
controllers/util/solr_scale_util.go
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml
tests/e2e/resource_utils_test.go
tests/e2e/solrcloud_scaling_test.go

Fixes #688 
The test I added didn't fail without the fixes, but I believe that's because of the PVCs that come with KiND...

Fix early deletion of PVCs during scale down

---

docs/solr-cloud/solr-cloud-crd.md

Resolves #679
Updated the security.json template in SolrCloud CRD documentation to include permission for `/admin/info/system path` so that it matches the actual security.json generated by Solr Operator.

Update security.json template in solr-cloud-crd.md to include permission for /admin/info/system path

---

controllers/solrcloud_controller_basic_auth_test.go
controllers/util/solr_security_util.go

Removes some extraneous output from liveness/readiness/startup probes that use the `bin/solr auth` command.

SOLR-17216: Cleanup command-based Solr probe output

---

helm/solr/README.md

Solr uses variations of the blurb below to describe itself on solr.apache.org, in the ref-guide, READMEs, etc:
> Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene [...]
This has served us well for years, but a few reasons call for a refresh:
1. Copies of this description have varied apart over time and need realigned
2. The description misses (or underplays) some of Solr's newer features (e.g. vector search)
3. Longer forms of the description emphasize features that aren't meaningful differentiators (e.g. XML-based APIs, scalability) in today's landscape.
This PR (along with accompanying changes to the main repo and website) updates and unifies the language the project uses to describe itself.

SOLR-16295: Modernize helm-chart project description

---

controllers/util/prometheus_exporter_util.go

a re-fix for #694 as the used query parameter has to be 'name[]' instead of name**s**[]
according to the used HTTPServer code (0.16.0 in Solr 9 or 0.2.0 in Solr 8.11)
https://github.com/prometheus/client_java/blob/ed0d7ae3b57a3986f6531d1a37db031a331227e6/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java#L153

fix: do not return metrics for prom-exporter probes re-fix (#694)

---

controllers/solrcloud_controller_basic_auth_test.go
controllers/util/solr_security_util.go
docs/development.md
helm/solr-operator/Chart.yaml
tests/e2e/solrcloud_security_json_test.go
tests/e2e/test_utils_test.go

This is primarily intended as a fix for https://github.com/apache/solr-operator/issues/731 and https://github.com/apache/solr-operator/issues/720.
This PR switches the setup-zk initcontainer from using the zkcli to `solr zk ...`. The zkcli is deprecated and will be removed in Solr 10. Also, this PR fixes bootstrapping with a custom security.json that was broken in v9.7. 
Please see comments in implementation.
I've updated the unit tests, and added an integration test for bootstrapping with a custom security.json. Below is the output of running that test:
```
make e2e-tests TEST_FILTER="E2E - SolrCloud - Security JSON"
...
Will run 1 of 28 specs
Running in parallel across 3 processes
SSSSSSSSSSSSSSSSSSSSSSSSSSS•
Ran 1 of 28 Specs in 82.823 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 …
```

fix(solr-zk) Switch from zkcli to solr zk command line

---

helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml

Operator users may host the image in their own repositories, protected by authentication.  Accept an imagePullSecret to facilitate these use cases.
Closes #718

Allow imagePullSecret in operator helm chart

---

README.md
docs/solr-cloud/README.md
docs/solr-cloud/solr-cloud-crd.md

The Solr-operator only has support for running Solr in "cloud" mode, as evidenced by the required ZK coordinates and even the name of the 'solrcloud' custom resource.  But there are few explicit mentions of this in the README or project docs.
This commit tweaks the docs to make this slightly more explicit.

Clarify lack of 'standalone' Solr support

---

api/v1beta1/common_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/solr.apache.org_solrclouds.yaml
config/crd/bases/solr.apache.org_solrprometheusexporters.yaml
controllers/solrcloud_controller_test.go
controllers/util/common.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml
helm/solr/README.md
helm/solr/templates/_custom_option_helpers.tpl
helm/solr/values.yaml

An alternate approach to #489.
#702 attempts to solve the same underlying issue by giving the Solr container in our STS template a hardcoded SecurityContext.  But that effort is, at the time of writing, stalled out: partly due to questions about whether the hardcoded SecurityContext would be too restrictive for some usecases, and partly due to an inability to test in the relevant environments.
This PR takes a different approach by leaving the securityContext unset by default, and instead giving interested users the ability to specify an arbitrary securityContext as a part of their SolrCloud (or as a 'solr' helm chart setting).  A securityContext can be provided in the resource YAML at `.spec.customSolrKubeOptions.podOptions.containerSecurityContext` (or using the …

Allow users to configure Solr container's SecurityContext 

---

hack/release/smoke_test/verify_all.sh

A variable 'artifact' was being referenced outside of the for-in loop that created it.

Fix unset-var bug in 'verify_all.sh' script

---

hack/release/upload/upload_crds.sh
hack/release/upload/upload_helm.sh

After a "passing" RC, the wizard has RMs download the CRDs and helm charts from a 'staging' area on dist.apache.org and then upload them to the final location.  We have scripts to do this, but these were broken recently when dist.apache.org changed its robots.txt to disallow unknown "crawlers".
This commit gets our scripting working again by tweaking a `wget` invocation to not strictly obey the robots.txt for dist.apache.org, which likely isn't intended for restricting foundation-internal usecases such as ours.

Workaround dist.apache.org download restrictions

---

controllers/solrcloud_controller_basic_auth_test.go
controllers/util/solr_security_util.go

Apparently if you invoke `solr zk` you need to pass in the `--zk-host` argument as it will not read the environment variable `ZK_HOST`.

fix the solr zk invocation

---

tests/scripts/manage_e2e_tests.sh

Not all environments set particular `RAW_GINKGO` args, causing `make e2e-tests` to fail with an "unset variable" related error.
This commit tweaks our `manage_e2e_tests.sh` script to guard against this case.

Prevent RAW_GINKGO unset error in e2e tests

---

example/test_solrcloud.yaml
example/test_solrcloud_backuprepos.yaml
example/test_solrcloud_private_repo.yaml
example/test_solrcloud_toleration_example.yaml
example/test_solrprometheusexporter.yaml

Several examples referenced the Solr 8.7, and other versions outside the currently supported range (which currently starts at 8.11).

Use supported Solr version in examples

---

helm/solr/README.md

8.8 is no longer supported by the operator (and is ancient in general); update the 'solr' helm chart README to use a slightly more modern version.

Update reference to out-of-range Solr version

---

controllers/solrcloud_controller.go
docs/running-the-operator.md
docs/upgrade-notes.md
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml

Adds this to `values.yaml`:
```
development: false
logger: {}
#encoder: json
#level: error
#stacktraceLevel: error
```
Docs:
**Note** that today zap "Development" mode has been the default, but this PR changes that to `false`, triggering production mode by default, and thus also log-level INFO and encoding to JSON. This is perhaps a bit much change in a minor version even if it is easy for users to tailor it. At the same time it feels wrong that development is the default mode. We could keep the default of development=true and change it to false in v1.0?
Fixes #778

Configure operator logging in helm chart
