Makefile
config/default/manager_image_patch.yaml
config/operators/solr_operator.yaml

*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
**Additional context**
Add any other context about your contribution here.

Upgrading to version 0.1.3

---

api/v1beta1/solrbackup_types.go

Fixed an infinite loop while setting defaults for backup CRDs. Issue found by @sepulworld .

Fixing infinite loop while setting defaults for backup

---

README.md

Fix helm readme link

---

example/test_solrprometheusexporter.yaml

*Issue number of the reported bug or feature request: #50*
Changed the test prometheus exporter to use the cloud reference, which should work if the cloud itself works.

Fix the prometheus exporter example

---

controllers/util/zk_util.go

This should fix the travis tests.

Fixing int to string conversion

---

controllers/util/collection_util.go

*Issue number of the reported bug or feature request: Fixes #98*
A parameter was missing while logging an error.

Fixed logging in Collection Deletion.

---

README.md

*Issue number of the reported bug or feature request: Fixes #101*
Added documentation for installing build dependencies.

Adding step in Readme to install build deps

---

docs/charts/index.yaml
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/values.yaml

Signed-off-by: Balaji Sankaranarayanan <bsankaranara@bloomberg.net>
Releasing v0.2.6 of the Solr Operator

Cutting release version v0.2.6 of the Solr Operator

---

docs/charts/index.yaml
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/values.yaml

Signed-off-by: Balaji Sankaranarayanan <bsankaranara@bloomberg.net>

Cutting release version v0.2.7 of the Solr Operator

---

.github/workflows/docker.yaml
.github/workflows/tests.yaml
Makefile
controllers/solrcloud_controller_ingress_test.go
controllers/solrcloud_controller_storage_test.go
controllers/solrcloud_controller_test.go
controllers/util/prometheus_exporter_util.go

Not exactly sure why the additional waits are needed in the tests, but will investigate.

Make github actions pass

---

docs/local_tutorial.md

Some improvements and updates to the tutorial

New version of dashbaord, use -w option for kubectl command

---

.asf.yaml
.github/workflows/docker.yaml
.github/workflows/tests.yaml
README.md
docs/local_tutorial.md
docs/running-the-operator.md
helm/solr-operator/README.md

Use main branch instead of master branch.

---

controllers/solrprometheusexporter_controller_test.go

Wait for another reconcile request to fix flaky test in CI

---

docs/solr-prometheus-exporter/README.md

Add instructions for using the Prometheus exporter with Prometheus stack

Improve Prom exporter docs

---

docs/solr-cloud/solr-cloud-crd.md

To make it more clear, could not find it anywhere else (not tested, nope it is correct)

Document what yaml keys to use for connectionInfo

---

config/rbac/role.yaml
controllers/solrcloud_controller.go
helm/solr-operator/templates/role.yaml

Helm chart no longer works as of this PR:
https://github.com/apache/lucene-solr-operator/pull/217
This should fix the issue.

Fix Ingress API group for RBAC rules.

---

docs/solr-cloud/managed-updates.md
docs/solr-cloud/solr-cloud-crd.md
docs/solr-prometheus-exporter/README.md

Would be good to add this to more of the features, but I don't know have enough context to label everything correctly.

Add note about versions supporting log4j.xml

---

README.md
docs/running-the-operator.md
docs/upgrade-notes.md
helm/solr-operator/README.md

Related to #222
This includes the warning that used to live in the README, as well as general guidelines around upgrading the Solr Operator.

Add separate documentation page for Upgrade Notes

---

Makefile
build/Dockerfile
build/build.sh
docs/development.md
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/values.yaml
main.go
version/version.go

Part of #243
Will allow us to have one location of the "current" version of a branch.

Add better versioning control in project.

---

config/rbac/role.yaml
controllers/solrcloud_controller.go
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/templates/role.yaml

- Ability to not use the Zookeeper Operator in the Solr Operator Helm Chart
- Add missing RBAC for finalizers (Resolves #263)

Changes to address issues found in v0.3.0 RC2

---

.asf.yaml
README.md
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md

Now live at: https://solr.apache.org/operator/

Add information about the official operator site.

---

docs/local_tutorial.md
docs/upgrading-to-apache.md
hack/test-upgrade.sh

Thanks @thelabdude and @sigram for noticing the issues.

Various small fixes for the tutorial and upgrade notes.

---

Makefile
api/v1beta1/solrbackup_types.go
api/v1beta1/solrcloud_types.go
api/v1beta1/solrprometheusexporter_types.go
hack/config/add_crds_roles_headers.sh
hack/config/copy_crds_roles_helm.sh

This should fix any issues with duplicate information in CRD files after running `make check-manifests`.

Fix issues with linting. Better solution for testing changes.

---

api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
controllers/solrcloud_controller.go
controllers/solrcloud_controller_test.go
controllers/util/solr_update_util.go
controllers/util/solr_update_util_test.go
dependency_licenses.csv
docs/solr-cloud/solr-cloud-crd.md
go.mod
go.sum
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml
helm/solr/README.md
helm/solr/templates/solrcloud.yaml
helm/solr/values.yaml

Ability to provide a cron-schedule for automatic restarts

---

docs/upgrade-notes.md
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml

Resolves #286
See linked issue for information on the removed deprecations.

Remove deprecations for v0.4.0 release.

---

docs/solr-cloud/solr-cloud-crd.md

(Approve and merge in one step welcome for this PR.)

s/his/this typo(?) fix in solr-cloud-crd.md

---

hack/release/smoke_test/smoke_test.sh
hack/release/smoke_test/test_cluster.sh
hack/release/wizard/releaseWizard.py
hack/release/wizard/releaseWizard.yaml

- New downloads page on the Solr Operator site
- New location of changelog
- Fix GPG Loading in release wizard
- Add Kubernetes version option for smoketest
- Fix communication for release

Change information in release wizard

---

docs/solr-cloud/solr-cloud-crd.md
helm/solr/README.md

Clear up difference between SolrCloud CRD and Solr Helm chart options

---

docs/running-the-operator.md
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
helm/solr-operator/templates/deployment.yaml
helm/solr-operator/values.yaml
main.go

Enable leader election for the operator by default.

---

Makefile
controllers/util/backup_util.go
hack/release/smoke_test/smoke_test.sh
hack/release/smoke_test/test_cluster.sh
hack/release/smoke_test/test_source.sh
hack/release/wizard/releaseWizard.yaml
helm/solr/README.md

Add smoke tester for this feature.

Fix incremental backups for volume repos.

---

helm/solr/Chart.yaml
helm/solr/templates/solrcloud.yaml

Fix zk.externalAddress in Solr Helm chart

---

api/v1beta1/solrcloud_types.go
docs/upgrade-notes.md
helm/solr-operator/Chart.yaml
helm/solr/Chart.yaml
helm/solr/README.md

Change default Solr version to 8.11

---

NOTICE
config/dependencies/zookeeper_cluster_crd.yaml
docs/development.md
docs/upgrade-notes.md
hack/headers/zookeeper-operator-header.yaml.txt
hack/release/artifacts/create_crds.sh
hack/zk-operator/update-crd.sh
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
versions.props

Resolves #396 
Strangely I think the `controllers/zk-api` directory already had code from v0.2.13 instead of v0.2.12.

Upgrade the zookeeper-operator to v0.2.13

---

Makefile

- Set explicit version for go-licenses
- Install kustomize via "go install"

Improve build-dependency installation

---

controllers/solrcloud_controller_storage_test.go
controllers/util/solr_util.go
helm/solr-operator/Chart.yaml

Fix volume mounts for PVCs with custom names

---

NOTICE
config/dependencies/zookeeper_cluster_crd.yaml
controllers/zk_api/zkcluster.go
docs/development.md
docs/upgrade-notes.md
hack/headers/zookeeper-operator-header.yaml.txt
hack/zk-operator/update-crd.sh
helm/solr-operator/Chart.yaml
helm/solr-operator/README.md
versions.props

Upgrade Zookeeper Operator dep to 0.2.14

---

controllers/solrcloud_controller_externaldns_test.go
controllers/solrcloud_controller_ingress_test.go
controllers/solrcloud_controller_test.go
controllers/solrcloud_controller_tls_test.go
controllers/solrprometheusexporter_controller_test.go
controllers/solrprometheusexporter_controller_tls_test.go
controllers/util/prometheus_exporter_util.go
controllers/util/solr_util.go
helm/solr-operator/Chart.yaml

Add app-protocol for all services

---

api/v1beta1/solrprometheusexporter_types.go
controllers/controller_utils_test.go
controllers/solrprometheusexporter_controller.go
controllers/solrprometheusexporter_controller_test.go
controllers/util/prometheus_exporter_util.go
docs/solr-prometheus-exporter/README.md
docs/upgrade-notes.md
hack/release/smoke_test/test_cluster.sh
helm/solr-operator/Chart.yaml

Use the Solr image as the default Prom Exp image

---

.run/Template Ginkgo.run.xml
Makefile
README.md
dev-docs/idea-tests.md
hack/idea/ginkgo-run.sh
hack/idea/idea-setup.txt
hack/release/artifacts/bundle_source.sh

Users will just need to run `make idea` first.

Allow tests to run in IntelliJ & GoLand

---

hack/release/smoke_test/test_cluster.sh

This fixes a bug in the smoketester wherein we attempted to 'upgrade' a
helm package that had previously been removed during some mid-execution
cleanup.

Refactor helm logic in test_cluster.sh

---

api/v1beta1/solrbackup_types.go
api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrbackups.yaml
config/crd/bases/solr.apache.org_solrclouds.yaml
controllers/util/solr_update_util.go
controllers/util/solr_util.go
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml

Fixes #479
Also updating some descriptions in the SolrCloud CRD.

Fix bug with named PVCs

---

api/v1beta1/solrbackup_types.go
api/v1beta1/solrcloud_types.go
config/crd/bases/solr.apache.org_solrclouds.yaml
controllers/controller_utils_test.go
controllers/solrbackup_controller.go
controllers/solrcloud_controller.go
controllers/solrprometheusexporter_controller.go
helm/solr-operator/Chart.yaml
helm/solr-operator/crds/crds.yaml
tests/e2e/resource_utils_test.go

Patch Solr resource statuses instead of updating them

---

.github/workflows/e2e-tests.yaml
dev-docs/e2e-testing.md
docs/upgrade-notes.md
hack/release/smoke_test/test_cluster.sh
helm/solr-operator/Chart.yaml
helm/solr/Chart.yaml
tests/e2e/test_utils_test.go
tests/scripts/manage_e2e_tests.sh

Set minimum Kubernetes version to v1.22

---

controllers/solrcloud_controller_externaldns_test.go
controllers/solrcloud_controller_ingress_test.go
controllers/solrcloud_controller_test.go
controllers/solrcloud_controller_tls_test.go
controllers/util/solr_util.go
helm/solr-operator/Chart.yaml

Fix appProtocol issue for non-TLS SolrClouds

---

controllers/util/prometheus_exporter_util.go
helm/solr-operator/Chart.yaml

Do not return metrics for liveness probe

---

controllers/util/common.go

Fixes #761 
The new feature forgot to add an update to the podTemplate for the new field being used.

Fix upgrade to v0.9 by updating pod readiness gates

---

controllers/solrcloud_controller_test.go
controllers/solrcloud_controller_zk_test.go
controllers/util/solr_util.go
helm/solr-operator/Chart.yaml

This is already done in an init container

Don't use post start hook for zk chroot creation
